#!/usr/bin/env bash
set -euo pipefail

BASE_URL="${OPENCODE_PROXY_BASE_URL:-http://127.0.0.1:${PORT:-8787}}"

# Claude Code appends /v1/messages to ANTHROPIC_BASE_URL.
export ANTHROPIC_BASE_URL="$BASE_URL"
export ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-opencode-local-proxy}"
export ANTHROPIC_CUSTOM_MODEL_OPTION="${ANTHROPIC_CUSTOM_MODEL_OPTION:-claude-sonnet-4-6}"
export ANTHROPIC_CUSTOM_MODEL_OPTION_NAME="${ANTHROPIC_CUSTOM_MODEL_OPTION_NAME:-OpenCode Go}"
export ANTHROPIC_CUSTOM_MODEL_OPTION_DESCRIPTION="${ANTHROPIC_CUSTOM_MODEL_OPTION_DESCRIPTION:-OpenCode Go through local proxy}"
export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="${CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC:-1}"
export CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS="${CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS:-1}"

exec claude "$@"
